[package]
org = "ballerinax"
name = "financial.ISO20022ToSwiftMT"
version = "0.9.0"
distribution = "2201.10.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org="ballerinax"
name="swiftmt"
version="1.2.0"
repository="local"
